apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap/base-nginx-configmap.yaml
- configmap/base-server-configmap.yaml
- cronjob/base-cronjob.yaml
- deployment/base-deploy.yaml
- deployment/base-worker-deploy.yaml
- hpa/base-pod-autoscaler.yaml
- hpa/base-worker-pod-autoscaler.yaml
- ingress/base-ingress.yaml
- secretproviderclass/base-secretprovider.yaml
- service/base-service.yaml
# - pdb/base-pdb.yaml
