apiVersion: batch/v1
kind: CronJob
metadata:
  name: school-cronjob
  labels:
    app: school-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: school-cronjob
        spec:
          serviceAccountName: school-service
          volumes:
            - name: school-secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: managex-school-secrets
          containers:
            - name: school-cronjob
              image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_school:stage-ffc19e9a7b9946d9a1f915a7ec5cec70d7fe02aa-MNX-1639-PR-3410"
              command: ["php", "/var/www/html/artisan", "schedule:run"]
              volumeMounts:
                - name: school-secrets
                  mountPath: "/var/www/html/.env"
                  subPath: ".env"
                  readOnly: true
          restartPolicy: OnFailure
